---
title: "Body measurements"
author: "Amelia Ritger"
date: "8/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(gtools)
library(lubridate)
library(ggpmisc) #use for adding regression line equation to ggplot

```

## Load data
```{r}
data <- read_csv("data/Measurements.csv") %>% 
  clean_names()
```

## Tidy data
```{r}
# convert NAs to 9999 for minimum value calculation next
data_no_na <- data %>%
  replace_na(list(dry_mass_plus_vial_g_day_1="9999")) %>%
  replace_na(list(dry_mass_plus_vial_g_day_2="9999")) %>%
  replace_na(list(dry_mass_plus_vial_g_day_3="9999")) %>%
  replace_na(list(dry_mass_plus_vial_g_day_4="9999")) %>%
  replace_na(list(dry_mass_plus_vial_g_day_5="9999")) %>%
  replace_na(list(dry_mass_plus_vial_g_day_6="9999")) %>%
  replace_na(list(dry_mass_plus_vial_g_day_7="9999"))

# Take the measurements, do algebra
measure <- data_no_na %>%
  mutate(oral_disk_mm = (oral_disk_diameter_mm_a + oral_disk_diameter_mm_b)/2) %>%
  mutate(basal_disk_mm = (basal_disk_diameter_mm_a + basal_disk_diameter_mm_b)/2) %>%
  mutate(wet_mass_g = wet_mass_plus_vial_g-vial_mass_g) %>%
  mutate(min_dry_mass_plus_vial_g = pmin(dry_mass_plus_vial_g_day_2, dry_mass_plus_vial_g_day_3,dry_mass_plus_vial_g_day_4,dry_mass_plus_vial_g_day_5, dry_mass_plus_vial_g_day_6, dry_mass_plus_vial_g_day_7)) %>%
  mutate(dry_mass_g = as.numeric(min_dry_mass_plus_vial_g)-vial_mass_g) %>%
  select(number, id, oral_disk_mm, basal_disk_mm, mouth_length_mm, vial_mass_g, min_dry_mass_plus_vial_g, wet_mass_g, dry_mass_g) %>% 
  filter(is.na(dry_mass_g)==FALSE) %>% 
  mutate(dry_mass_g=ifelse(dry_mass_g < 0, 0, dry_mass_g)) #make negative values (samples 85, 160) zero

measure_dry <- measure %>% 
  filter(dry_mass_g>0) #remove zero values

```

# Plot some stuff
```{r}
formula1 <- y ~ poly(x,2)
formula2 <- y ~ poly(x,3)

# oral disk ~ mouth length, dry mass/wet mass ~ oral disk/mouth length
ggplot(measure, aes(x=basal_disk_mm, y=dry_mass_g)) +
  geom_point() +
  #geom_point(aes(color=id)) + # plot points colored by ID
  geom_smooth(method="lm", formula= (y ~ poly(x,2)), color="blue", fill="blue", linetype="dashed") +
  geom_smooth(method="lm", formula= (y ~ poly(x,3)), color="red", fill="red", linetype="dashed") +
  #geom_smooth(method = "lm", se = FALSE, formula = y ~ exp(x))
  labs(x="Oral Disk Diameter (mm)", y="Wet mass (g)") +
  theme_bw() +
  stat_poly_eq(formula = formula1, 
                aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
                parse = TRUE) +
  stat_poly_eq(formula = formula2, 
                aes(label = paste(..eq.label.., ..rr.label.., sep = "~~~")), 
               label.y = "bottom", label.x = "right",
                parse = TRUE)
```

